import React from 'react';

export default function Home({ onGetStarted }) {
  return (
    <div className="space-y-0">
      {/* Hero Section - Full width with dramatic background */}
      <section className="relative w-full h-screen bg-black text-white overflow-hidden flex items-center justify-center">
        {/* Background Image with Overlay */}
        <div 
          className="absolute inset-0 bg-cover bg-center"
          style={{
            backgroundImage: "url('https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=2000&q=80')",
          }}
        >
          <div className="absolute inset-0 bg-gradient-to-r from-black/90 via-black/70 to-black/40"></div>
        </div>

        {/* Hero Content */}
        <div className="max-w-6xl mx-auto text-center relative z-10 px-6">
          <h1 className="text-6xl md:text-7xl lg:text-8xl font-black mb-6 leading-tight tracking-tight uppercase">
            START YOUR FITNESS
          </h1>
          <p className="text-lg md:text-xl mb-4 text-gray-300 max-w-2xl mx-auto">
            World is committed to making participation in the harassment experience for everyone, regardless of level of experience.
          </p>
          <p className="text-2xl md:text-3xl font-bold mb-10 text-white">
            Starting From <span className="text-[#7B9669]">$0</span>/Month
          </p>
          
          {/* CTA Buttons */}
          <div className="flex flex-wrap justify-center gap-4 mb-16">
            <button
              onClick={onGetStarted}
              className="border-2 border-white hover:border-[#7B9669] text-white hover:bg-[#7B9669]/10 px-8 py-3.5 rounded text-lg font-semibold transition-all flex items-center gap-2"
            >
              Get Started
              <span>→</span>
            </button>
            <button
              onClick={onGetStarted}
              className="bg-[#7B9669] hover:bg-[#8aa678] text-white px-8 py-3.5 rounded text-lg font-semibold transition-all"
            >
              Try Free Demo
            </button>
          </div>

          {/* Pagination Dots */}
          <div className="flex justify-center gap-2 mb-12">
            <div className="w-2 h-2 rounded-full bg-white"></div>
            <div className="w-2 h-2 rounded-full bg-[#7B9669]"></div>
            <div className="w-2 h-2 rounded-full bg-white"></div>
          </div>
        </div>

        {/* Stats Bar */}
        <div className="absolute bottom-0 left-0 right-0 bg-black/50 backdrop-blur-sm border-t border-white/10">
          <div className="max-w-7xl mx-auto px-6 py-8">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
              <div>
                <div className="text-4xl md:text-5xl font-bold text-white mb-2">+4</div>
                <div className="text-sm text-gray-400 uppercase tracking-wide">Workout Types</div>
              </div>
              <div>
                <div className="text-4xl md:text-5xl font-bold text-white mb-2">+100</div>
                <div className="text-sm text-gray-400 uppercase tracking-wide">Exercise Library</div>
              </div>
              <div>
                <div className="text-4xl md:text-5xl font-bold text-white mb-2">+500</div>
                <div className="text-sm text-gray-400 uppercase tracking-wide">Happy Users</div>
              </div>
              <div>
                <div className="text-4xl md:text-5xl font-bold text-white mb-2">+20</div>
                <div className="text-sm text-gray-400 uppercase tracking-wide">Expert Plans</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="bg-gradient-to-b from-gray-50 to-white py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-black text-slate-900 mb-4 uppercase">Why Choose FlexCore</h2>
            <p className="text-lg text-slate-600 max-w-2xl mx-auto">
              Everything you need to achieve your fitness goals in one powerful platform
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {[
              { 
                icon: '🎯', 
                title: 'Smart AI Plans',
                desc: 'Personalized workout plans generated by AI based on your goals, experience level, and available equipment.',
                color: 'from-[#7B9669] to-[#8aa678]'
              },
              { 
                icon: '📚', 
                title: '100+ Exercises',
                desc: 'Comprehensive exercise library with detailed instructions, form guides, and video demonstrations.',
                color: 'from-[#8aa678] to-[#BAC8B1]'
              },
              { 
                icon: '📊', 
                title: 'Track Progress',
                desc: 'Monitor your fitness journey with advanced analytics, workout history, and performance insights.',
                color: 'from-[#7B9669] to-[#8aa678]'
              },
              { 
                icon: '🏆', 
                title: 'Free Forever',
                desc: 'Full access to all features completely free. No hidden fees, no credit card required.',
                color: 'from-[#8aa678] to-[#BAC8B1]'
              },
            ].map((item, i) => (
              <div 
                key={i}
                className="relative group"
              >
                <div className="absolute inset-0 bg-gradient-to-br opacity-0 group-hover:opacity-10 rounded-2xl transition-opacity duration-300"
                  style={{backgroundImage: `linear-gradient(135deg, #7B9669, #BAC8B1)`}}
                ></div>
                <div className="relative bg-white p-8 rounded-2xl shadow-lg hover:shadow-2xl transition-all duration-300 border border-gray-100 hover:border-[#7B9669]/30 h-full">
                  <div className="text-5xl mb-4">{item.icon}</div>
                  <h3 className="text-xl font-bold text-slate-900 mb-3">{item.title}</h3>
                  <p className="text-slate-600 leading-relaxed">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works - Modern Dark Section */}
      <section className="bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-black mb-4 uppercase">How It Works</h2>
            <p className="text-lg text-gray-300 max-w-3xl mx-auto">
              Get started in three simple steps and transform your fitness journey
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8 relative">
            {/* Connection Lines */}
            <div className="hidden md:block absolute top-20 left-0 right-0 h-1 bg-gradient-to-r from-transparent via-[#7B9669] to-transparent"></div>
            
            {[
              {
                step: '01',
                icon: '👤',
                title: 'Create Your Profile',
                desc: 'Set up your account with your fitness goals, experience level, and preferences. Takes less than 2 minutes.',
              },
              {
                step: '02',
                icon: '⚡',
                title: 'Generate Your Plan',
                desc: 'Our AI creates a customized workout plan tailored to your goals, schedule, and available equipment.',
              },
              {
                step: '03',
                icon: '📈',
                title: 'Track & Succeed',
                desc: 'Log workouts, monitor progress, and watch yourself get stronger with detailed analytics.',
              },
            ].map((step, i) => (
              <div key={i} className="relative">
                <div className="relative z-10 bg-gradient-to-br from-slate-800 to-slate-900 p-8 rounded-2xl border-2 border-[#7B9669]/30 hover:border-[#7B9669] transition-all duration-300 group hover:transform hover:scale-105">
                  <div className="absolute -top-6 left-8 bg-[#7B9669] text-white w-12 h-12 rounded-full flex items-center justify-center font-bold text-xl shadow-lg">
                    {step.step}
                  </div>
                  <div className="text-6xl mb-4 mt-4 group-hover:scale-110 transition-transform">{step.icon}</div>
                  <h3 className="text-2xl font-bold mb-3 text-white">{step.title}</h3>
                  <p className="text-gray-300 leading-relaxed">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-16 grid md:grid-cols-2 gap-4 max-w-4xl mx-auto">
            {[
              { icon: '✓', text: 'Adaptive plans for all fitness levels' },
              { icon: '✓', text: 'Multiple workout types: Strength, Cardio, HIIT, Flexibility' },
              { icon: '✓', text: 'Comprehensive exercise library with detailed guides' },
              { icon: '✓', text: 'Real-time progress tracking and workout history' },
            ].map((item, i) => (
              <div key={i} className="flex items-center gap-3 bg-slate-800/50 p-4 rounded-lg border border-slate-700 hover:border-[#7B9669]/50 transition-colors">
                <span className="text-[#7B9669] text-xl font-bold">{item.icon}</span>
                <span className="text-sm text-gray-200">{item.text}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials - Modern Grid */}
      <section className="bg-white py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-black text-slate-900 mb-4 uppercase">
              Success Stories
            </h2>
            <p className="text-lg text-slate-600">
              Real transformations from people like you
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                stars: 5,
                text: 'FlexCore completely changed my approach to fitness. The AI-generated plans are spot-on and the progress tracking keeps me motivated!',
                author: 'Alex Martinez',
                role: 'Lost 25 lbs',
                image: 'https://i.pravatar.cc/150?img=12'
              },
              {
                stars: 5,
                text: 'Love the variety! I can switch between strength and cardio seamlessly. The exercise library is incredible with clear instructions.',
                author: 'Jessica Rivers',
                role: 'Gained Muscle',
                image: 'https://i.pravatar.cc/150?img=45'
              },
              {
                stars: 5,
                text: 'Best fitness app I\'ve used. Free, powerful, and actually works. The workout generator saves me hours of planning every week.',
                author: 'Mike Thompson',
                role: 'Marathon Runner',
                image: 'https://i.pravatar.cc/150?img=33'
              },
            ].map((testimonial, idx) => (
              <div key={idx} className="bg-gradient-to-br from-gray-50 to-white p-8 rounded-2xl shadow-lg hover:shadow-2xl transition-all duration-300 border border-gray-100 hover:border-[#7B9669]/30">
                <div className="flex gap-1 mb-4">
                  {[...Array(testimonial.stars)].map((_, i) => (
                    <span key={i} className="text-[#7B9669] text-xl">★</span>
                  ))}
                </div>
                <p className="text-slate-700 mb-6 leading-relaxed italic">"{testimonial.text}"</p>
                <div className="flex items-center gap-4 pt-4 border-t border-gray-200">
                  <img 
                    src={testimonial.image} 
                    alt={testimonial.author}
                    className="w-12 h-12 rounded-full object-cover"
                  />
                  <div>
                    <p className="font-bold text-slate-900">{testimonial.author}</p>
                    <p className="text-sm text-[#7B9669]">{testimonial.role}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing - Bold CTA Section */}
      <section className="bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white py-20 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl md:text-5xl font-black mb-6 uppercase">
            Ready to Transform?
          </h2>
          <p className="text-xl text-gray-300 mb-12">
            Get unlimited access to everything. Forever free. No credit card required.
          </p>
          
          <div className="bg-gradient-to-br from-[#7B9669] to-[#8aa678] p-1 rounded-3xl max-w-2xl mx-auto mb-8">
            <div className="bg-slate-900 p-10 rounded-3xl">
              <div className="mb-6">
                <div className="text-6xl font-black text-white mb-2">
                  $0
                  <span className="text-2xl text-gray-400 font-normal">/forever</span>
                </div>
                <p className="text-[#BAC8B1] font-semibold">Free Forever Plan</p>
              </div>
              
              <ul className="space-y-4 mb-8 text-left">
                {[
                  'Unlimited AI-powered workout generation',
                  'Access to all 4 workout types',
                  'Complete 100+ exercise library',
                  'Full progress tracking & analytics',
                  'Workout history & logging',
                  'Personalized fitness profile',
                  'No ads, no limitations',
                  'Always free - no tricks',
                ].map((feature, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <span className="text-[#7B9669] text-xl mt-0.5 flex-shrink-0">✓</span>
                    <span className="text-gray-200">{feature}</span>
                  </li>
                ))}
              </ul>
              
              <button
                onClick={onGetStarted}
                className="w-full bg-gradient-to-r from-[#7B9669] to-[#8aa678] hover:from-[#8aa678] hover:to-[#7B9669] text-white py-4 rounded-xl text-lg font-bold transition-all transform hover:scale-105 shadow-lg"
              >
                Start Free Now →
              </button>
              
              <p className="text-sm text-gray-400 mt-4">
                Join thousands of users transforming their fitness
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="bg-black text-white py-16 px-6">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Your Transformation Starts Today</h2>
          <p className="text-gray-300 mb-8 text-lg">
            Join FlexCore and discover what you're truly capable of
          </p>
          <button
            onClick={onGetStarted}
            className="bg-gradient-to-r from-[#7B9669] to-[#8aa678] hover:from-[#8aa678] hover:to-[#7B9669] text-white px-10 py-4 rounded-xl text-lg font-bold transition-all transform hover:scale-105 shadow-lg"
          >
            Get Started Free
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-900 text-gray-300 py-12 px-6 border-t border-slate-800">
        <div className="max-w-6xl mx-auto grid md:grid-cols-4 gap-8 mb-8">
          <div>
            <h3 className="font-bold text-lg mb-4 text-white">FlexCore</h3>
            <p className="text-sm text-gray-400">
              Your AI-powered fitness companion. Transform your body, transform your life.
            </p>
          </div>
          <div>
            <h3 className="font-bold text-lg mb-4 text-white">Features</h3>
            <ul className="space-y-2 text-sm">
              <li><button onClick={onGetStarted} className="hover:text-[#7B9669] transition">Workout Generator</button></li>
              <li><button onClick={onGetStarted} className="hover:text-[#7B9669] transition">Exercise Library</button></li>
              <li><button onClick={onGetStarted} className="hover:text-[#7B9669] transition">Progress Tracking</button></li>
              <li><button onClick={onGetStarted} className="hover:text-[#7B9669] transition">Workout History</button></li>
            </ul>
          </div>
          <div>
            <h3 className="font-bold text-lg mb-4 text-white">Resources</h3>
            <ul className="space-y-2 text-sm">
              <li><button onClick={onGetStarted} className="hover:text-[#7B9669] transition">How It Works</button></li>
              <li><button onClick={onGetStarted} className="hover:text-[#7B9669] transition">Feedback</button></li>
              <li><button className="hover:text-[#7B9669] transition">FAQ</button></li>
              <li><button className="hover:text-[#7B9669] transition">Support</button></li>
            </ul>
          </div>
          <div>
            <h3 className="font-bold text-lg mb-4 text-white">Company</h3>
            <ul className="space-y-2 text-sm">
              <li><button className="hover:text-[#7B9669] transition">About FlexCore</button></li>
              <li><button className="hover:text-[#7B9669] transition">Contact Us</button></li>
              <li><button className="hover:text-[#7B9669] transition">Privacy Policy</button></li>
              <li><button className="hover:text-[#7B9669] transition">Terms of Service</button></li>
            </ul>
          </div>
        </div>
        <div className="border-t border-slate-800 pt-8 text-center text-sm text-gray-400">
          <p className="mb-2">© 2025 FlexCore. All rights reserved.</p>
          <p>Your personalized AI fitness companion</p>
        </div>
      </footer>
    </div>
  );
}
